# Generated by Django 5.2.7 on 2025-10-25 12:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', validators=[core.models.validate_video_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='posts/photos/'),
        ),
    ]
